export const CHANNEL_MOCK = {
  'channels':
    [{
      'id': '20085',
      'number': '10',
      'name': 'CANAL IBEROAMERICANO',
      'hd': false,
      'image': 'https://clarovideocdn3.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SS/CANALIBEROAMERICANO_t-290x163.png',
      'group_id': '780506',
      'liveref': 'ibero',
      'epg_url': 'tv://channel.',
      'source_uri': '',
      'provider_metadata_id': 2,
      'provider_metadata_name': 'NAGRA',
      'group': {
        'common': {
          'id': '780506',
          'title': 'CANAL IBEROAMERICANO',
          'title_episode': null,
          'title_uri': 'CANAL-IBEROAMERICANO',
          'title_original': 'CANAL IBEROAMERICANO',
          'description': 'CANAL IBEROAMERICANO (CDN MX)',
          'description_large': 'CANAL IBEROAMERICANO (CDN MX)',
          'short_description': null,
          'image_large': 'https://clarovideocdn7.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SS/CANALIBEROAMERICANOWHORIZONTAL.jpg?size=675x380',
          'image_medium': 'https://clarovideocdn5.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SS/CANALIBEROAMERICANOWVERTICAL.jpg?size=200x300',
          'image_small': 'https://clarovideocdn7.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SS/CANALIBEROAMERICANOWHORIZONTAL.jpg?size=290x163',
          'image_still': null,
          'image_background': 'https://clarovideocdn7.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/CLEAN/CANALIBEROAMERICANO_e-1280x720.jpg',
          'url_imagen_t1': 'https://clarovideocdn8.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/CLEAN/CANALIBEROAMERICANOWVERTICAL.jpg?size=200x300',
          'url_imagen_t2': 'https://clarovideocdn0.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/CLEAN/CANALIBEROAMERICANOWHORIZONTAL.jpg?size=290x163',
          'image_base_horizontal': 'https://clarovideocdn4.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SS/CANALIBEROAMERICANOWHORIZONTAL.jpg',
          'image_base_vertical': 'https://clarovideocdn2.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SS/CANALIBEROAMERICANOWVERTICAL.jpg',
          'image_base_square': 'https://clarovideocdn2.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SS/CANALIBEROAMERICANOWCUADRADO.jpg',
          'image_clean_horizontal': 'https://clarovideocdn7.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/CLEAN/CANALIBEROAMERICANOWHORIZONTAL.jpg',
          'image_clean_vertical': 'https://clarovideocdn5.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/CLEAN/CANALIBEROAMERICANOWVERTICAL.jpg',
          'image_clean_square': 'https://clarovideocdn5.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/CLEAN/CANALIBEROAMERICANOWCUADRADO.jpg',
          'image_sprites': 'https://clarovideocdn8.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SPRITES/CANALIBEROAMERICANO-SPRITEBAR.jpg',
          'image_frames': 'https://clarovideocdn4.clarovideo.net/PELICULAS/CANALIBEROAMERICANO/EXPORTACION_WEB/SPRITES/CANALIBEROAMERICANO-00h-00m-00s-00f.jpg',
          'image_trickplay': '',
          'image_external': null,
          'duration': null,
          'date': '20190207140412',
          'year': null,
          'preview': 'false',
          'season_number': null,
          'episode_number': null,
          'format_types': 'free',
          'live_enabled': '1',
          'live_type': '1',
          'live_ref': 'ibero',
          'source_uri': '',
          'timeshift': null,
          'votes_average': 5,
          'rating_code': 'G',
          'proveedor_name': 'AMCO',
          'proveedor_code': 'amco',
          'encoder_tecnology': { 'id': '3', 'desc': 'HARMONIC_VOS' },
          'recorder_technology': { 'id': null, 'desc': null },
          'resource_name': null,
          'rollingcreditstime': null,
          'rollingcreditstimedb': null,
          'is_series': false,
          'channel_number': '10',
        },
      },
      'events': [{
        'channel_id': '20085',
        'source_uri': '',
        'id': '1966607378',
        'name': 'Verano Divertido',
        'description': 'Verano Divertido.',
        'talent': null,
        'date_begin': '2024/03/13 07:00:00',
        'date_end': '2024/03/13 14:00:00',
        'unix_begin': 1710334800,
        'unix_end': 1710360000,
        'duration': '07:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': '88c2fabf7000',
        'ext_ncont_id': '171455423805',
        'ext_nevt_id': '88c2fabf7000',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'Verano Divertido',
        'ext_ep_original_name': null,
        'ext_series_id': '171455402516',
        'ext_season_id': '21',
        'ext_episode_id': '289',
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+16',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': 'Cultural',
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20085',
        'source_uri': '',
        'id': '1966607387',
        'name': 'La UNAM Responde',
        'description': 'Programa de TV UNAM.',
        'talent': null,
        'date_begin': '2024/03/13 14:00:00',
        'date_end': '2024/03/13 15:00:00',
        'unix_begin': 1710360000,
        'unix_end': 1710363600,
        'duration': '01:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': 'fcdf6e499afd',
        'ext_ncont_id': '191229440933',
        'ext_nevt_id': 'fcdf6e499afd',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': 'MEX',
        'ext_original_name': 'La UNAM Responde',
        'ext_ep_original_name': null,
        'ext_series_id': '191229420163',
        'ext_season_id': '20',
        'ext_episode_id': '770',
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+16',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': 'Cultural',
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20085',
        'source_uri': '',
        'id': '1966607396',
        'name': '1,5 El Límite',
        'description': 'Programa de ATEI - Canal 44 UDG.',
        'talent': null,
        'date_begin': '2024/03/13 15:00:00',
        'date_end': '2024/03/13 15:30:00',
        'unix_begin': 1710363600,
        'unix_end': 1710365400,
        'duration': '00:30:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': 'ab57d5594b14',
        'ext_ncont_id': '555551405059',
        'ext_nevt_id': 'ab57d5594b14',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': '1,5 El Límite',
        'ext_ep_original_name': null,
        'ext_series_id': '555551384948',
        'ext_season_id': '20',
        'ext_episode_id': '111',
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+16',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': 'Cultural',
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }],
    }, {
      'id': '20084',
      'number': '504',
      'name': 'CLARO SPORTS',
      'hd': false,
      'image': 'https://clarovideocdn7.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SS/CLAROSPORTS_t-290x163.png',
      'group_id': '771505',
      'liveref': 'clarosportsmxhd',
      'epg_url': 'tv://channel.',
      'source_uri': '',
      'provider_metadata_id': 2,
      'provider_metadata_name': 'NAGRA',
      'group': {
        'common': {
          'id': '771505',
          'title': 'CLARO SPORTS',
          'title_episode': null,
          'title_uri': 'CLARO-SPORTS',
          'title_original': 'CLARO SPORTS',
          'description': 'CLARO SPORTS MX PUSH',
          'description_large': 'CLARO SPORTS MX PUSH',
          'short_description': null,
          'image_large': 'https://clarovideocdn1.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SS/CLAROSPORTSWHORIZONTAL.jpg?size=675x380',
          'image_medium': 'https://clarovideocdn9.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SS/CLAROSPORTSWVERTICAL.jpg?size=200x300',
          'image_small': 'https://clarovideocdn1.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SS/CLAROSPORTSWHORIZONTAL.jpg?size=290x163',
          'image_still': null,
          'image_background': 'https://clarovideocdn1.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/CLEAN/CLAROSPORTS_e-1280x720.jpg',
          'url_imagen_t1': 'https://clarovideocdn2.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/CLEAN/CLAROSPORTSWVERTICAL.jpg?size=200x300',
          'url_imagen_t2': 'https://clarovideocdn4.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/CLEAN/CLAROSPORTSWHORIZONTAL.jpg?size=290x163',
          'image_base_horizontal': 'https://clarovideocdn8.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SS/CLAROSPORTSWHORIZONTAL.jpg',
          'image_base_vertical': 'https://clarovideocdn6.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SS/CLAROSPORTSWVERTICAL.jpg',
          'image_base_square': 'https://clarovideocdn6.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SS/CLAROSPORTSWCUADRADO.jpg',
          'image_clean_horizontal': 'https://clarovideocdn1.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/CLEAN/CLAROSPORTSWHORIZONTAL.jpg',
          'image_clean_vertical': 'https://clarovideocdn9.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/CLEAN/CLAROSPORTSWVERTICAL.jpg',
          'image_clean_square': 'https://clarovideocdn9.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/CLEAN/CLAROSPORTSWCUADRADO.jpg',
          'image_sprites': 'https://clarovideocdn2.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SPRITES/CLAROSPORTS-SPRITEBAR.jpg',
          'image_frames': 'https://clarovideocdn8.clarovideo.net/PELICULAS/CLAROSPORTS/EXPORTACION_WEB/SPRITES/CLAROSPORTS-00h-00m-00s-00f.jpg',
          'image_trickplay': '',
          'image_external': null,
          'duration': null,
          'date': '20180524190613',
          'year': null,
          'preview': 'false',
          'season_number': null,
          'episode_number': null,
          'format_types': 'susc',
          'live_enabled': '1',
          'live_type': '1',
          'live_ref': 'clarosportsmxhd',
          'source_uri': '',
          'timeshift': null,
          'votes_average': 4,
          'rating_code': 'G',
          'proveedor_name': 'AMCO',
          'proveedor_code': 'amco',
          'encoder_tecnology': { 'id': '3', 'desc': 'HARMONIC_VOS' },
          'recorder_technology': { 'id': '1', 'desc': 'HARMONICS' },
          'resource_name': null,
          'rollingcreditstime': null,
          'rollingcreditstimedb': null,
          'is_series': false,
          'channel_number': '504',
        },
      },
      'events': [{
        'channel_id': '20084',
        'source_uri': '',
        'id': '1966605137',
        'name': 'Sultanes De Monterrey Vs Charros De Jalisco - LMSF - J1',
        'description': 'La Liga Mexicana de Sóftbol llevará a cabo su histórica temporada en enero del 2024. Los seis equipos que participarán en esta primera edición abrirán sus puertas a un nuevo público que por primera vez podrá disfrutar de esta disciplina de manera organizada.',
        'talent': null,
        'date_begin': '2024/03/13 12:00:00',
        'date_end': '2024/03/13 14:00:00',
        'unix_begin': 1710352800,
        'unix_end': 1710360000,
        'duration': '02:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': '60d0f3846496',
        'ext_ncont_id': '025232779233',
        'ext_nevt_id': '60d0f3846496',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'Sultanes De Monterrey Vs Charros De Jalisco - LMSF - J1',
        'ext_ep_original_name': null,
        'ext_series_id': null,
        'ext_season_id': null,
        'ext_episode_id': null,
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': 'Deporte',
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20084',
        'source_uri': '',
        'id': '1966605148',
        'name': 'Deportes En Claro',
        'description': 'Los hechos deportivos más importantes de la jornada.',
        'talent': null,
        'date_begin': '2024/03/13 14:00:00',
        'date_end': '2024/03/13 15:00:00',
        'unix_begin': 1710360000,
        'unix_end': 1710363600,
        'duration': '01:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': '0410b14bf88a',
        'ext_ncont_id': '315098632557',
        'ext_nevt_id': '0410b14bf88a',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'Deportes En Claro',
        'ext_ep_original_name': null,
        'ext_series_id': '315098541573',
        'ext_season_id': '90',
        'ext_episode_id': '984',
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': 'Deporte',
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20084',
        'source_uri': '',
        'id': '1966605157',
        'name': 'Claro Sports En W Radio',
        'description': 'El mejor programa deportivo en México lo tenemos nosotros: Claro Sports por MVS. Un espacio radiofónico de una hora de duración en el que ofrecemos el mejor análisis de la actualidad deportiva, así como entrevistas, mesas de debate y mucho más.',
        'talent': null,
        'date_begin': '2024/03/13 15:00:00',
        'date_end': '2024/03/13 16:00:00',
        'unix_begin': 1710363600,
        'unix_end': 1710367200,
        'duration': '01:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': '3ae33ff2f85a',
        'ext_ncont_id': '323544422092',
        'ext_nevt_id': '3ae33ff2f85a',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'Claro Sports En W Radio',
        'ext_ep_original_name': null,
        'ext_series_id': '323544331107',
        'ext_season_id': '90',
        'ext_episode_id': '985',
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': 'Deporte',
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20084',
        'source_uri': '',
        'id': '1966605166',
        'name': 'La Jornada',
        'description': 'Vive toda la acción del deporte a nivel mundial en todas sus disciplinas.',
        'talent': null,
        'date_begin': '2024/03/13 16:00:00',
        'date_end': '2024/03/13 17:00:00',
        'unix_begin': 1710367200,
        'unix_end': 1710370800,
        'duration': '01:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': '21538cc1a56d',
        'ext_ncont_id': '308974325995',
        'ext_nevt_id': '21538cc1a56d',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'La Jornada',
        'ext_ep_original_name': null,
        'ext_series_id': '308974235009',
        'ext_season_id': '90',
        'ext_episode_id': '986',
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': 'Deporte',
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }],
    }, {
      'id': '20651',
      'number': '510',
      'name': 'ENGLISH PREMIER LEAGUE 1',
      'hd': false,
      'image': 'https://clarovideocdn7.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SS/ENGLISHPREMIERLEAGUE1_t-290x163.png',
      'group_id': '1042215',
      'liveref': 'epl1',
      'epg_url': 'tv',
      'source_uri': '',
      'provider_metadata_id': 2,
      'provider_metadata_name': 'NAGRA',
      'group': {
        'common': {
          'id': '1042215',
          'title': 'ENGLISH PREMIER LEAGUE 1',
          'title_episode': null,
          'title_uri': 'ENGLISH-PREMIER-LEAGUE-1',
          'title_original': 'ENGLISH PREMIER LEAGUE 1',
          'description': 'ENGLISH PREMIER LEAGUE 1 MÉXICO',
          'description_large': 'ENGLISH PREMIER LEAGUE 1',
          'short_description': null,
          'image_large': 'https://clarovideocdn1.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SS/ENGLISHPREMIERLEAGUE1WHORIZONTAL.jpg?size=675x380',
          'image_medium': 'https://clarovideocdn9.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SS/ENGLISHPREMIERLEAGUE1WVERTICAL.jpg?size=200x300',
          'image_small': 'https://clarovideocdn1.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SS/ENGLISHPREMIERLEAGUE1WHORIZONTAL.jpg?size=290x163',
          'image_still': null,
          'image_background': 'https://clarovideocdn1.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/CLEAN/ENGLISHPREMIERLEAGUE1_e-1280x720.jpg',
          'url_imagen_t1': 'https://clarovideocdn2.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/CLEAN/ENGLISHPREMIERLEAGUE1WVERTICAL.jpg?size=200x300',
          'url_imagen_t2': 'https://clarovideocdn4.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/CLEAN/ENGLISHPREMIERLEAGUE1WHORIZONTAL.jpg?size=290x163',
          'image_base_horizontal': 'https://clarovideocdn8.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SS/ENGLISHPREMIERLEAGUE1WHORIZONTAL.jpg',
          'image_base_vertical': 'https://clarovideocdn6.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SS/ENGLISHPREMIERLEAGUE1WVERTICAL.jpg',
          'image_base_square': 'https://clarovideocdn6.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SS/ENGLISHPREMIERLEAGUE1WCUADRADO.jpg',
          'image_clean_horizontal': 'https://clarovideocdn1.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/CLEAN/ENGLISHPREMIERLEAGUE1WHORIZONTAL.jpg',
          'image_clean_vertical': 'https://clarovideocdn9.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/CLEAN/ENGLISHPREMIERLEAGUE1WVERTICAL.jpg',
          'image_clean_square': 'https://clarovideocdn9.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/CLEAN/ENGLISHPREMIERLEAGUE1WCUADRADO.jpg',
          'image_sprites': 'https://clarovideocdn2.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SPRITES/ENGLISHPREMIERLEAGUE1-SPRITEBAR.jpg',
          'image_frames': 'https://clarovideocdn8.clarovideo.net/PARAMOUNT/PELICULAS/ENGLISHPREMIERLEAGUE1/EXPORTACION_WEB/SPRITES/ENGLISHPREMIERLEAGUE1-00h-00m-00s-00f.jpg',
          'image_trickplay': '',
          'image_external': null,
          'duration': null,
          'date': '20220622144103',
          'year': null,
          'preview': 'false',
          'season_number': null,
          'episode_number': null,
          'format_types': 'susc',
          'live_enabled': '1',
          'live_type': '1',
          'live_ref': 'epl1',
          'source_uri': '',
          'timeshift': null,
          'votes_average': 4,
          'rating_code': 'G',
          'proveedor_name': 'PARAMOUNT',
          'proveedor_code': 'paramount',
          'encoder_tecnology': { 'id': '3', 'desc': 'HARMONIC_VOS' },
          'recorder_technology': { 'id': null, 'desc': null },
          'resource_name': null,
          'rollingcreditstime': null,
          'rollingcreditstimedb': null,
          'is_series': false,
          'channel_number': '510',
        },
      },
      'events': [{
        'channel_id': '20651',
        'source_uri': '',
        'id': '1966610780',
        'name': 'English Premier League 1',
        'description': 'Programación English Premier League 1',
        'talent': null,
        'date_begin': '2024/03/13 11:00:00',
        'date_end': '2024/03/13 17:00:00',
        'unix_begin': 1710349200,
        'unix_end': 1710370800,
        'duration': '06:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': 'c43ff732b8c7',
        'ext_ncont_id': '280550997660',
        'ext_nevt_id': 'c43ff732b8c7',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'English Premier League 1',
        'ext_ep_original_name': null,
        'ext_series_id': null,
        'ext_season_id': null,
        'ext_episode_id': null,
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': null,
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20651',
        'source_uri': '',
        'id': '1966610789',
        'name': 'English Premier League 1',
        'description': 'Programación English Premier League 1',
        'talent': null,
        'date_begin': '2024/03/13 17:00:00',
        'date_end': '2024/03/13 23:00:00',
        'unix_begin': 1710370800,
        'unix_end': 1710392400,
        'duration': '06:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': '461c704cb3c1',
        'ext_ncont_id': '280550997660',
        'ext_nevt_id': '461c704cb3c1',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'English Premier League 1',
        'ext_ep_original_name': null,
        'ext_series_id': null,
        'ext_season_id': null,
        'ext_episode_id': null,
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': null,
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20651',
        'source_uri': '',
        'id': '1966610798',
        'name': 'English Premier League 1',
        'description': 'Programación English Premier League 1',
        'talent': null,
        'date_begin': '2024/03/13 23:00:00',
        'date_end': '2024/03/14 05:00:00',
        'unix_begin': 1710392400,
        'unix_end': 1710414000,
        'duration': '06:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': 'f6254909d38a',
        'ext_ncont_id': '280550997660',
        'ext_nevt_id': 'f6254909d38a',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'English Premier League 1',
        'ext_ep_original_name': null,
        'ext_series_id': null,
        'ext_season_id': null,
        'ext_episode_id': null,
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': null,
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20651',
        'source_uri': '',
        'id': '1966610807',
        'name': 'English Premier League 1',
        'description': 'Programación English Premier League 1',
        'talent': null,
        'date_begin': '2024/03/14 05:00:00',
        'date_end': '2024/03/14 11:00:00',
        'unix_begin': 1710414000,
        'unix_end': 1710435600,
        'duration': '06:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': '81f96589dadd',
        'ext_ncont_id': '280550997660',
        'ext_nevt_id': '81f96589dadd',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'English Premier League 1',
        'ext_ep_original_name': null,
        'ext_series_id': null,
        'ext_season_id': null,
        'ext_episode_id': null,
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': null,
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }, {
        'channel_id': '20651',
        'source_uri': '',
        'id': '1966610816',
        'name': 'English Premier League 1',
        'description': 'Programación English Premier League 1',
        'talent': null,
        'date_begin': '2024/03/14 11:00:00',
        'date_end': '2024/03/14 17:00:00',
        'unix_begin': 1710435600,
        'unix_end': 1710457200,
        'duration': '06:00:00',
        'language': 'esp',
        'type': '0',
        'group_id': null,
        'confirmado': null,
        'id_empleado': null,
        'tms_id': null,
        'event_alf_id': 'fbc66dd9fbc6',
        'ext_ncont_id': '280550997660',
        'ext_nevt_id': 'fbc66dd9fbc6',
        'ext_actors': null,
        'ext_director': null,
        'ext_year': null,
        'ext_country': null,
        'ext_original_name': 'English Premier League 1',
        'ext_ep_original_name': null,
        'ext_series_id': null,
        'ext_season_id': null,
        'ext_episode_id': null,
        'ext_language': 'spa',
        'ext_serie_short_desc': null,
        'ext_serie_desc': null,
        'image_base_horizontal': '',
        'image_base_vertical': '',
        'image_base_square': '',
        'ext_eventimage_name': '',
        'ext_eventimage_name_base': '',
        'ext_catchup': '0',
        'ext_startover': '0',
        'ext_recordable': '0',
        'parental_rating': '+12',
        'aud_stereo': '0',
        'aud_dolby': '0',
        'vid_black_and_white': '0',
        'dvb_content': null,
        'user_content': null,
        'group_rel': null,
        'gmt': -6,
      }],
    }],
  'total': 34,
}